- name: Stop pgsql service
  service:
    name: postgresql-9.5
    state: stopped
  when: "'dev02' in inventory_hostname_short"

-  file:
    path: /opt/pgsql/archivedir/
    state: directory
    owner: postgres
    group: postgres
    mode: 0777

- name: Vytvorit slozku pro archiv HA
  file: path="{{ pgsql_95_main_directory }}"/mnt/server/archivedir state=directory
  when: "'dev02' in inventory_hostname_short"

- name: Nastaveni konfiguracniho souboru postgresql.conf
  template:
    src: postgresql-slave.conf.j2
    dest: "{{ pgsql_95_data_directory }}/postgresql.conf"
  when: "'dev02' in inventory_hostname_short"

- name: Nastaveni recovery.conf
  template:
    src: recovery.conf.j2
    dest: "{{ pgsql_95_data_directory }}/recovery.conf"
  when: "'dev02' in inventory_hostname_short"     

- name: Start pgsql service
  service:
    name: postgresql-9.5
    state: started
