- name: Stop pgsql service
  service:
    name: postgresql-9.5
    state: stopped
  when: "'dev02' in inventory_hostname_short"

- name: Restart pgsql service
  service:
    name: postgresql-9.5
    state: restarted
  when: "'dev01' in inventory_hostname_short"

- name: "Configure-slaves: remove existing data dir"
  file: path="/var/lib/pgsql/9.5/data" state=absent
  when: slavnuke and 'dev02' in inventory_hostname_short

- name: "Configure-slaves: initialize new postgresql cluster"
  command: "pg_basebackup -c fast -X stream -h {{ ip_mgmt_01 }} -U {{ pgsql_replication_user }} -D /var/lib/pgsql/9.5/data"
#  sudo: True
#  sudo_user: postgres
  become: true
  become_method: su
  become_user: postgres
  when: "'dev02' in inventory_hostname_short"
